### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by yordiverbeeck** [0xn33t/capacitor-widgetsbridge-plugin#2]
I'm pretty new to Capacitor/iOS development and I have some issues setting up this plugin.
I have no issue implementing the capacitor part and I have the basic widget showing "Not Set".

But I can't get them to communicate with each other. Do you mind explaining the correct setup a bit in the Readme?

**Comment by 0xn33t** [comment]
Hi,

Have you created your own app group? Make sure that your app and widget are using the same user's defaults keys in getting and setting values.

**Comment by yordiverbeeck** [comment]
Shoot! Didn't know about the app groups, thanks for hinting me in that direction.
All working now, thanks for making the plugin! 🙏
