### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by NeroN7F** [0xn33t/capacitor-widgetsbridge-plugin#3]
Hi. Could you please provide sort of step by step guide ? Absolutely no idea how to integrate plugin with current application. I've already set up the app group and stuck now

**Comment by 0xn33t** [comment]
Hi, 

1- Open the Runner.xcworkspace of your project
2- Add new Widget Extension
3- Add the capability (App Group) to your App and Widget Extension
4- Make sure that both targets use the same App Group
5- Make sure that your app and widget are using the same user's defaults keys in getting and setting values

**Comment by NeroN7F** [comment]
Thanks
