### ISSUE TITLE
Add support for Capacitor v6

### ISSUE THREAD

**Issue by benmarsh** [0xn33t/capacitor-widgetsbridge-plugin#8]
Hi, it would be great if support could be added to the plugin for v6 of Capacitor.

- Release: https://ionic.io/blog/announcing-capacitor-6-0
- Changelog: https://github.com/ionic-team/capacitor/blob/main/CHANGELOG.md

Thanks

**Comment by 0xn33t** [comment]
Updated!

**Comment by benmarsh** [comment]
Awesome, thanks @0xn33t :)
